# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='mod_date',
            new_name='mod_time',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 9, 9, 28, 41, 591700, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
